name: Sync Collector component docs

on:
  workflow_dispatch:
  schedule:
    # At 03:00 UTC, every day
    - cron: 0 3 * * *

# Declare default permissions as read only.
permissions: read-all

jobs:
  sync-collector-docs:
    name: Sync Collector component documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    # Only run on official repo, not forks
    if: github.repository == 'open-telemetry/opentelemetry.io'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Use CLA approved github bot
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

      - name: Create otelbot GitHub App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_DOCS_APP_ID }}
          private-key: ${{ secrets.OTELBOT_DOCS_PRIVATE_KEY }}

      - name: Sync collector documentation
        run: bash .github/scripts/collector-sync.sh
        env:
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
          GITHUB_REPOSITORY: open-telemetry/opentelemetry.io
